# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1

jobs:
    build:
      branches:
        only:
          - master # list of branches to build

    docker:
      # specify the version here
      - image: circleci/elixir:1.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |
            echo -e "**********************\\n* EXLIXIR STONE TEST *\\n**********************"
        # Check if all files are well formatted -- If failed, exit.
            mix format --check-formatted
        # Gets all out of date dependencies
            mix deps.get
        # Updates the given dependencies
            mix deps.update
        # Run all unit test in /test
            mix test
