# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details

version: 2
jobs:
  Elixir-stone:
      docker:
        # specify the version here
        - image: circleci/elixir:1.8

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/postgres:9.4

      working_directory: ~/repo

      steps:
        - checkout
        - run:
            name: say Hello
            command: echo -e "**********************\\n* EXLIXIR STONE TEST *\\n**********************"
        - run:
            name: Check if all files are well formatted -- If failed, exit.
            command: mix format --check-formatted
        - run:
            name: Install Hex locally
            command: mix local.hex --force
        - run:
            name: Gets all out of date dependencies
            command: mix deps.get
        # - run:
        #     name: Updates the given dependencies
        #     command: mix deps.update
        - run:
            name: Run all unit test in /test
            command: mix test



workflows:
  version: 2
  build_and_test:
    jobs:
      - Elixir-stone:
          filters:
            branches:
              only:
                - master # list of branches to build
